title: "Alex Doe's Homepage"
page-top-title: "Alex Doe"
top-section-bg-text: "Artificial Intelligence"
home-subtitle: "Alex Doe | 艾力克斯·杜"
copyright-text: "© Alex Doe 2023–2025. All Rights Reserved."
social_links:
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/AlexDoe"
  - label: "Google Scholar"
    icon: "ai ai-google-scholar"
    url: "https://scholar.google.com/citations?user=XXXX"
  - label: "Email"
    icon: "fas fa-envelope"
    url: "mailto:alex.doe@example.com"
